### ISSUE TITLE
Dynamic Permission Request

### ISSUE THREAD

**Issue by marcellov7** [Videodock/cordova-plugin-chromecast#4]
Hi there 👋,

First off, I want to express my gratitude for the ongoing support you provide for the Cordova Chromecast plugin.

I have a suggestion regarding user experience enhancement. Is it feasible to implement a feature where permissions for Bluetooth are requested (for iOS) only when the user initiates the Chromecast functionality (and not at first app startup)? 

This would significantly reduce post-installation friction for users of apps utilizing the plugin.

Thank you once again for your valuable support!

**Comment by ChristiaanScheermeijer** [comment]
Hi @marcellov7,

Sorry for not responding earlier. Thank you for your gratitude! Happy to hear others are using this plugin as well 😄 

I believe that the Bluetooth permissions aren't requested anymore in the latest iOS cast SDK. We have updated the SDK recently and will update it again this week. 

The Local Network permission modal still shows after calling the `initialize()` method. With this, it is possible to initialize the Chromecast plugin (and session) when the user clicks the Cast button, but then the button should be visible all times. 

In our app, we call `initialize` when the video playback starts. We show the cast button when a receiver is available.

Which commit are you using?

**Comment by ChristiaanScheermeijer** [comment]
@marcellov7 let us know if you still have problems with the plugin!
